### ISSUE TITLE
issue in validation 

### ISSUE THREAD

**Issue by harshittpandey** [bradtraversy/loginapp#11]
hey, please correct me if i am wrong,
if you don't enter password2 then it is showing password doesnt match instead of passsword2 field empty.
and,
if you don't enter email then it is showing email is not valid along with email is empty.

**Comment by Saspect-IO** [comment]
If you look at the validation section of the code you will see that one validator clause is set for password2. So whether it is empty or incorrect  it will not be equal to password 1. 

With regards to email two validator clauses are set on it so it will trigger both if it is empty because an empty field is both invalid and empty.  
And will trigger one clause if you enter an invalid email. 

Try entering an invalid email like missing the  @ symbol and see.
